name: Convert Markdown to PDF

on:
  # push:
  #   paths:
  #     - '**/*.md'  # Trigger on Markdown file changes
  # pull_request:
  #   paths:
  #     - '**/*.md'  # Trigger on pull requests modifying Markdown files
  workflow_dispatch:  # Enable manual triggering

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Pandoc and rsvg-convert
        run: |
          sudo apt-get update
          echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin fonts-dejavu ttf-mscorefonts-installer
          fc-cache -f -v  # Update font cache

      # Step 3: Insert PDF Metadata
      - name: Add Metadata to Markdown Files
        run: |
          for file in *.md; do
            # Uncomment one of the following date formats

            # For YYYY-MM
            sed -i "1i ---\ntitle: \"My Amazing Book\"\nsubtitle: \"Exploring Windows Files and Folders\"\nauthor: \"Mark McDow\"\ndate: \"$(date +'%Y-%m')\"\nkeywords: [Windows, Files, Folders, Forensics]\nabstract: >\n  This book dives into the intricacies of Windows files and folders, providing insights for IT professionals and enthusiasts alike.\nlang: en-US\nfontsize: 12pt\ngeometry: margin=1in\nmainfont: \"DejaVu Sans Mono\"\n---\n" "$file"

            # For ISO 8601 (YYYY-MM-DD)
            # sed -i "1i ---\ntitle: \"My Amazing Book\"\nsubtitle: \"Exploring Windows Files and Folders\"\nauthor: \"Mark McDow\"\ndate: \"$(date +'%Y-%m-%d')\"\nkeywords: [Windows, Files, Folders, Forensics]\nabstract: >\n  This book dives into the intricacies of Windows files and folders, providing insights for IT professionals and enthusiasts alike.\nlang: en-US\nfontsize: 12pt\ngeometry: margin=1in\nmainfont: \"DejaVu Sans Mono\"\n---\n" "$file"
          done

      # Step 3: Sanitize Markdown files for Latex error with Unicode and backslashes in .md
      - name: Preprocess Markdown Files
        run: |
          for file in *.md; do
            # Escape LaTeX special characters
            # sed -i 's|%|\\%|g; s|{|\\{|g; s|}|\\}|g; s|_|\\_|g; s|\\|\\\\|g' "$file"
            # Replace box-drawing characters
            # sed -i 's/├/|--/g; s/└/`--/g; s/│/|   /g; s/\xE2\x94\x80/--/g' "$file"
            # Remove trailing spaces and redundant blank lines
            sed -i 's/[[:space:]]*$//' "$file"
            sed -i '/^$/N;/^\n$/D' "$file"
          done

      # Step 4: Convert Markdown to PDF
      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdfs
          for file in *.md; do
            pandoc "$file" --pdf-engine=xelatex -V mainfont="DejaVu Sans Mono" -o "pdfs/${file%.md}.pdf" || echo "Failed to convert $file, skipping..."
          done

      # Step 5: Upload PDFs as Artifact
      - name: Upload PDFs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: markdown-pdfs
          path: pdfs/
