name: Convert Markdown to PDF

on:
  # push:
  #   paths:
  #     - '**/*.md'  # Trigger on Markdown file changes
  # pull_request:
  #   paths:
  #     - '**/*.md'  # Trigger on pull requests modifying Markdown files
  workflow_dispatch:  # Enable manual triggering

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Pandoc and rsvg-convert
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex librsvg2-bin fonts-dejavu ttf-mscorefonts-installer
          fc-cache -f -v  # Update font cache

      # Step 3: Pre-process Markdown files for Latex error with backslashes in .md
      - name: Sanitize Markdown Files
        run: |
          for file in *.md; do
            sed -i 's|\\|\\\\|g' "$file"
            sed -i 's/├/|--/g; s/└/`--/g; s/│/|   /g' "$file"
          done

      # Step 4: Convert Markdown to PDF
      - name: Convert Markdown to PDF
        run: |
          mkdir -p pdfs
          for file in *.md; do
            pandoc "$file" --pdf-engine=xelatex -V mainfont="Consolas" -o "pdfs/${file%.md}.pdf"
          done

      # Step 5: Upload PDFs as Artifact
      - name: Upload PDFs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: markdown-pdfs
          path: pdfs/
